version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
  pre_build:
    commands:
      - echo npm install
      - npm install
  build:
    commands:
      - echo building
      - npm run build

artifacts: 
  files:
    - "**/*"
  discard-paths: no
  base-directory: build